sudo: required
language: shell
os: linux
arch: ppc64le
group: power-focal
 
git:
  submodules: false
  depth: 10
 
services:
  - docker
 
env:
  matrix:
    - DISTRO=sle16sp0
 
before_install:
  # Workaround Travis CI timeout: keep-alive output every 5 minutes
  - while true; do echo "Still running..."; sleep 300; done &
 
  # Ensure full git fetch
  - git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
 
  # Pull the Docker image early
- REPO_URL="${REPO_URL:-icr.io/sys-kernelbackport}"
  - docker pull "${REPO_URL}/${DISTRO}" || true
 
install: []
 
branches:
  only:
    - master
 
script:
  # Login to Docker
- echo "${My_Password}" | docker login -u iamapikey --password-stdin icr.io
 
  # Ensure pulling the Docker image (again, in case before_install failed)
  - docker pull "${REPO_URL}/${DISTRO}"
 
  # Run the container and execute the update
  - docker run -v "$(pwd)":/root/kernels -w /root/kernels/ -it "${REPO_URL}/${DISTRO}" /root/kernels/.update \
      -f "${FTP3_Credentials}" -d "${DISTRO}" -n "${My_Name}" -e "${My_Email}"
