sudo: required
language: shell
os: linux
arch: ppc64le
group: power-focal

git:
  submodules: false
  depth: 10

services:
  - docker

env:
    matrix:
       - DISTRO=sle16sp0
    
install:
  - git config remote.origin.fetch +refs/heads/*:refs/remotes/origin/*

branches:
  only:
    - master

script:
  - REPO_URL="${REPO_URL:-icr.io/sys-kernelbackport}"
  - echo ${My_Password} | docker login -u iamapikey --password-stdin icr.io
  - docker pull ${REPO_URL}/${DISTRO}
  - docker run -v $(pwd):/root/kernels -w /root/kernels/ -it ${REPO_URL}/${DISTRO} /root/kernels/.update -f "${FTP3_Credentials}" -d "${DISTRO}" -n "${My_Name}" -e "${My_Email}"
